export const ADD_INGREDIENT='ADD';
export const REMOVE_INGREDIENT='REMOVE';
export const SET_INGREDIENTS='SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FAILED';

export const POST_ORDER_START='POST_ORDER_START';
export const POST_ORDER_SUCCESS='POST_ORDER_SUCCES';
export const POST_ORDER_FAIL='POST_ORDER_FAIL';

export const PURSHASE_BURGER_INIT='PURSHASE_BURGER_INIT';

export const FETCH_ORDERS_START='FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL='FETCH_ORDERS_FAIL';

